sudo: required
services:
  - docker

before_install:
  - docker build -t prodiptasengupta/multi-container -f ./client/Dockerfile.dev 

script:
  - docker run -e CI=true prodiptasengupta/multi-container npm run test -- --coverage

after_success:
  - docker build -t prodiptasengupta/multi-client ./client
  - docker build -t prodiptasengupta/multi-nginx ./nginx
  - docker build -t prodiptasengupta/multi-server ./server
  - docker build -t prodiptasengupta/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push prodiptasengupta/multi-client
  - docker push prodiptasengupta/multi-nginx
  - docker push prodiptasengupta/multi-server
  - docker push prodiptasengupta/multi-worker